
# Не трогайте если не знаете что делать
bStats: true
update-checker: true

update:
  enable: true
  time: 1800 # Интервал старта ивента в секундах

  # удалите строку msg если не нужен
  msg:
    - "Колизей был обновлён!"
    - "/warp war"
