license:
  key: "ВСТАВЬТЕ_СЮДА_ВАШ_КЛЮЧ_ЛИЦЕНЗИИ"

debug: false

update:
  enable: true
  time: 1800 # Интервал старта ивента в секундах

  # удалите строку msg если не нужен
  msg:
    - "Колизей был обновлён!"
    - "/warp war"
