name: TreexCastle
version: '2.2'
main: me.jetby.treexCastle.Main
api-version: '1.16'
load: POSTWORLD
authors: [ MrJetby ]
website: https://dsc.gg/treexstudio
depend:
  - DecentHolograms
softdepend:
  - PlaceholderAPI
commands:
  shulker: {}